[package]
name = "ncn-program-bls-router"
description = "NCN program bls router"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }


[dev-dependencies]
assert_matches = { workspace = true }
tempfile = "3.8"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
clap-markdown = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
hex = { workspace = true }
ncn-program-client = { workspace = true }
ncn-program-core = { workspace = true }
jito-bytemuck = { workspace = true }
rand = { workspace = true }
serde_with = { version = "3.0", features = ["hex"] }
solana-account-decoder = { workspace = true }
solana-client = { workspace = true }
solana-metrics = { workspace = true }
solana-rpc-client = { workspace = true }
solana-sdk = { workspace = true }
solana-program = { workspace = true }
spl-token = { workspace = true }
tokio = { workspace = true }
alloy = { version = "0.12.6" }
async-trait = "0.1"
alloy-primitives = "0.8.25"
alloy-signer = "0.12.6"
alloy-signer-local = "0.12.6"
alloy-provider = "0.12.6"
ark-bn254 = "0.5.0"
ark-ec = "0.5.0"
solana-bn254 = { workspace = true }
ark-ff = "0.5.0"
ark-serialize = "0.5.0"
bn254 = { git = "https://github.com/BreadchainCoop/bn254.git" }
bytes = "1.10.1"
commonware-codec = "0.0.56"
commonware-cryptography = "0.0.56"
commonware-macros = "0.0.56"
commonware-p2p = "0.0.56"
commonware-runtime = "0.0.56"
commonware-utils = "0.0.56"
eigen-crypto-bls = "0.5.0"
eigen-crypto-bn254 = "0.5.0"
futures = "0.3.31"
futures-util = "0.3.31"
governor = "0.6.3"
prometheus-client = "0.23.1"
prost = "0.13.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = { version = "2.5.4", features = ["serde"] }
num-bigint = "0.4"
commonware-eigenlayer = { git = "https://github.com/BreadchainCoop/commonware-avs-network-lookup" }
eigen-logging = "0.1.3"
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }

[build-dependencies]
prost-build = "0.13.5"
